<a href="https://colab.research.google.com/github/sierragl2019/Primer-repositorio/blob/main/tarea1_ejercicio3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np
p=np.zeros(13)
max=np.zeros(9)
A=np.array ([[1,9,17,25,-99,41,49,57],[2,10,18,26,-99,42,50,58],[-99,11,19,27,-99,-99,51,59],[4,12,20,28,-99,44,52,60],[5,-99,21,29,-99,45,-99,61],[6,14,22,-99,-99,46,54,62],[7,15,-99,-99,-99,47,55,-99],[8,16,24,-99,40,48,56,64]])
D=np.arange(0.4,0.8,0.01)
B=D.reshape(8,5)
C=np.concatenate((A, B),axis=1)

for i in range (0,12):
  sum=0
  for j in range (0,8):
    sum=sum+C[j][i]
  p[i]=sum/8


E=np.concatenate((C, p),axis=None)
F=E.reshape(9,13)


for i in range (0,9):
  v=0
  for j in range (0,12):
    if (F[i][j]>v):
      v=F[i][j]
    max[i]=v

m=max.reshape(9,1)
G=np.concatenate((F, m),axis=1)

print ("La matriz A es ")
print (A)

print ("La matriz B es ")
print (B)

print ("La matriz concatenada de A y B (matriz C) es ")
print (C)

print ("La matriz C con el promedio en la ultima fila (matriz F) es  ")
print (F)

print ("La matriz F con el numero maximo en la ultima columna (matriz G) es  ")
print (G)

La matriz A es 
[[  1   9  17  25 -99  41  49  57]
 [  2  10  18  26 -99  42  50  58]
 [-99  11  19  27 -99 -99  51  59]
 [  4  12  20  28 -99  44  52  60]
 [  5 -99  21  29 -99  45 -99  61]
 [  6  14  22 -99 -99  46  54  62]
 [  7  15 -99 -99 -99  47  55 -99]
 [  8  16  24 -99  40  48  56  64]]
La matriz B es 
[[0.4  0.41 0.42 0.43 0.44]
 [0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54]
 [0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64]
 [0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74]
 [0.75 0.76 0.77 0.78 0.79]]
La matriz concatenada de A y B (matriz C) es 
[[  1.     9.    17.    25.   -99.    41.    49.    57.     0.4    0.41
    0.42   0.43   0.44]
 [  2.    10.    18.    26.   -99.    42.    50.    58.     0.45   0.46
    0.47   0.48   0.49]
 [-99.    11.    19.    27.   -99.   -99.    51.    59.     0.5    0.51
    0.52   0.53   0.54]
 [  4.    12.    20.    28.   -99.    44.    52.    60.     0.55   0.56
    0.57   0.58   0.59]
 [  5.   -99.    21.    29.   -9